### ISSUE TITLE
UUID for Xcode 11.2

### ISSUE THREAD

**Issue by sinhpham** [BrainiumLLC/rust-xcode-plugin#9]
```
$ defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID
A74FBA51-FFEA-4409-B976-6FC3225A6F64
```

**Comment by francesca64** [comment]
Thanks for reporting this, and sorry for the delay!

This UUID is now in master, via PR #6: https://github.com/BrainiumLLC/rust-xcode-plugin/blob/18b1a461cfa0726caeb778f75ca9438fbf452c3d/Plug-ins/Rust.ideplugin/Contents/Info.plist#L44

Please let me know if you have any other issues!
